sudo: false

language: erlang
otp_release:
  - 22.0
  - 21.3

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libexpat1-dev

install: rebar3 compile
script:
  - rebar3 xref
  - rebar3 dialyzer
  - OTP_VSN=${TRAVIS_OTP_RELEASE}-1 ./build_docker_image.sh
  - ./test_docker_image.sh

cache:
  directories:
    - $HOME/.cache/rebar3
