version: "3.9"
services:
  amoc-master:
    hostname: "amoc-master"
    image: "amoc-arsenal-xmpp"
    ports:
      - "4000:4000"
    networks:
      - amoc-test-network
    environment:
      AMOC_GRAPHITE_HOST: '"${GRAPHITE_HOST:-host.docker.internal}"'
  amoc-worker:
    image: "amoc-arsenal-xmpp"
    scale: 2
    networks:
      - amoc-test-network
    environment:
      AMOC_GRAPHITE_HOST: '"${GRAPHITE_HOST:-host.docker.internal}"'
      AMOC_NODES: "['amoc_arsenal_xmpp@amoc-master']"
      AMOC_XMPP_SERVERS: '[[{host, <<"host.docker.internal">>}]]'
    entrypoint: [ "sh", "-c", 'AMOC_GRAPHITE_PREFIX="\"amoc.$${HOSTNAME}\"" /sbin/my_init']
networks:
  amoc-test-network:
