 # This is a basic workflow to help you get started with Actions

 name: CI

 # Controls when the action will run.
 on:
   # Triggers the workflow on push or pull request events but only for the master branch
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]

 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   test:
     name: OTP ${{matrix.otp}}
     strategy:
       matrix:
         otp: ['22.0', '21.3']
     runs-on: 'ubuntu-20.04'
     steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
       - uses: ErlGang/setup-erlang@v1.0.0
         with:
           otp-version: ${{ matrix.otp }}
       - name: Compile project
         run: rebar3 compile
       - name: run xref check
         run: rebar3 xref
       - name: run dializer check
         run: rebar3 dialyzer
       - name: build docker image
         run: ./travis/build_docker_image.sh
       - name: test docker image
         run: ./travis/test_docker_image.sh
