 name: CI

 # Controls when the action will run.
 on:
   # Triggers the workflow on push or pull request events but only for the master branch
   push:
     branches: [ master ]
   pull_request:
     branches: [ master ]

 jobs:
   test:
     name: OTP ${{matrix.otp}}
     strategy:
       matrix:
         otp: ['22.3', '21.3']
     runs-on: 'ubuntu-20.04'
     steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
       - uses: ErlGang/setup-erlang@v1.0.0
         with:
           otp-version: ${{ matrix.otp }}
       - name: Compile project
         run: ./rebar3 compile
       - name: run xref check
         run: ./rebar3 xref
       - name: run dialyzer check
         run: ./rebar3 dialyzer

   integration_test:
     name: docker container test with OTP ${{matrix.otp}}
     strategy:
       matrix:
         otp: ['22.3', '21.3']
     runs-on: 'ubuntu-20.04'
     env:
       OTP_RELEASE: ${{ matrix.otp }}
     steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
       - name: build docker image
         run: ./ci/build_docker_image.sh
       - name: test docker image
         run: ./ci/test_docker_image.sh
